modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="crystal_dimension"
version="1.0.0"
displayName="Crystal Dimension"
credits="Andus, Jasiekoo"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Blackstone"

[[dependencies.crystal_dimension]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




